[build-system]
requires = ["maturin>=0.14,<0.15"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]
python-source = "python"
module-name = "fasttextaug.rust_fasttextaug"
manifest-path = "rust/Cargo.toml"